---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: "${NAMESPACE}"
spec:
  tls:
  - secretName: "${TLS_SECRET}"
  backend:
    serviceName: your-service-name
    servicePort: 80
