---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lego
  namespace: "${NAMESPACE}"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lego-secret-update
  namespace: "${NAMESPACE}"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["${TLS_SECRET}"]
  verbs: ["get", "patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lego-secret-update
  namespace: "${NAMESPACE}"
subjects:
- kind: ServiceAccount
  name: lego
  namespace: "${NAMESPACE}"
roleRef:
  kind: Role
  name: lego-secret-update
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "${NAMESPACE}-lego-nfs"
  labels:
    volume: "${NAMESPACE}-lego-nfs"
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_HOSTNAME}"
    path: "${NFS_PATH}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lego-nfs
  namespace: "${NAMESPACE}"
spec:
  selector:
    matchLabels:
      volume: "${NAMESPACE}-lego-nfs"
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
